name: erca
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - bokeh
  - cartopy
  - xarray
  - cftime
  - intake
  - intake-esm=2021.8.17
  - intake-xarray=0.6.0
  - jupyterlab
  - jupyterlab_code_formatter
  - matplotlib=3.4.3
  - numpy=1.20.3
  - pandas=1.3.4
  - pyviz_comms=2.2.1
  - scipy=1.7.1
  - seaborn=0.11.2
  - pip:
    - aiohttp==3.8.1
    - aioitertools==0.10.0
    - aiosignal==1.2.0
    - cdsapi==0.5.1
    - dask==2022.5.0
    - fsspec==2022.3.0
    - gcsfs==2022.3.0
    - haversine==2.7.0
    - holoviews==1.15.3
    - hvplot==0.8.2
    - miditime==1.1.3
    - nc-time-axis==1.4.1
    - netcdf4==1.5.8
    - panel==0.14.2
    - pangeo-forge-recipes==0.8.3
    - pygame==2.1.2
    - pyhdf==0.10.5
    - pymannkendall==1.4.2
    - python-vlc==3.0.18121
    - zarr==2.11.3